### ISSUE TITLE
Attestation config format

### ISSUE THREAD

**Issue by rvolosatovs** [profianinc/steward#138]
In #107 a multitude of `X` and `X_blacklist` fields is added and not all of these are consistent.

How about we have a `[deny]` and `[allow]` sections instead?

E.g.:
```toml
[sgx.allow]
hash = "DEADBEEF"
signer = "BEEFDEAD"

[sgx.deny]
signer = "C0FFEE"
```

**Comment by rjzak** [comment]
* How would this look in code? Is this a simple Serde `rename`?
* What about other items in SGX and SNP? Would it be like below, and is that too many [sections]?:
```toml
[sgx.allow]
hash = "DEADBEEF"
signer = "BEEFDEAD"

[sgx.deny]
signer = "C0FFEE"

[sgx]
features = ["Debug", "ProvisioningKey", "EInitKey", "KSS"]
enclave_security_version = 0
enclave_product_id = 0
```
